### ISSUE TITLE
Task List (Iteration 1)

### ISSUE THREAD

**Issue by bit-bangin** [bit-bangin/GetYouTubeTranscript#3]
Task list for the project.

**Comment by bit-bangin** [comment]
## Task List

---

- [ ] Define the Scope & Requirements for the project.
>Clearly identify the problem and desired outcome.
>Define the functional and non-functional requirements.
>Assess feasibility and constraints.
- [ ] Set up the Programming Environment
>Choose and install the programming language
>Install necessary tools, libraries, dependencies for the project.
>Set up your coding environment - test and baseline.
- [ ] Collect sample YouTUbe URLs for Testing
> Collect a variety of sample YouTube URLs
- [ ] Create code to extract the video ID from the URL.
>Function to extract the video ID from a given URL.
- [ ] Create code to scrape YouTube to obtain the transcript.
>Function to scrape and extract necessary data. 
- [ ] Create code to clean and format given transcript.
>Create a function to reformat the transcript text.
>Remove uncessary data as needed.
- [ ] Create code to output the transcript
>Function that outputs the transcript to a given medium
>I.E.: console, file, program, database
- [ ] Integrate all parts into a main function/script.
>Write a main() function that brings together all of the previous functions. 
- [ ] Test the program.
>Use the sample URLs and test the program. 
>Take note of any bugs, problems
>Debug
- [ ] Document the code, write user intstructions
>Comment the code
>Consider writing user guides and instructions. 
- [ ] Review/Refine
>Review testing, determine next steps.
